name: Docker image (Python)

on:
  push:
    branches:
      - master
    paths:
      - '**/ci-python.yml'
      - 'python.Dockerfile'
      - 'python.entrypoint.sh'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.10.19, 3.11.14, 3.12.12, 3.13.9, 3.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Login to DockerHub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract first two elements
        id: extract
        run: |
          str="${{ matrix.python_version }}"
          IFS='.' read -ra arr <<< "$str"
          result="${arr[0]}.${arr[1]}"
          echo "result=$result" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          build-args: PYTHON_VERSION=${{ steps.extract.outputs.result }}
          context: .
          file: python.Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: "djoh/all-in-one:python${{ steps.extract.outputs.result }}"
          cache-from: type=registry,ref=djoh/all-in-one:buildcache_python${{ matrix.python_version }}
          cache-to: type=registry,ref=djoh/all-in-one:buildcache_python${{ matrix.python_version }},mode=max
